---
title: Home
layout: default
---

# SITE SETTINGS
#
# title appears in the header
title: JAMM425 Magazine Feature Writing
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: book
# author settings for cc-by, appears in the footer and credits
author: Will Simpson
# your github username for link [optional]
github_username: woodenzen
# year or date published
pub_year: 2024
# location of code, the full url to your github repository
source-code: https://github.com/woodenzen/JAMM425-Magazine-Feature-Writing

{% include toc.html %}

------

{% include template/credits.html %}
